stages:
  - test
  - deploy


test:
  stage: test
  script: echo $CI_PROJECT_DIR/


run:
  stage: deploy
  script:
    - echo "Deploying application"
    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /var/www/portal
    - echo "APPLICATIONS sucessfully copied"
    - pip3 install -r requirements.txt
    - echo "REQUIREMENTS sucessfully installed"
    - cp /var/www/portal/configs/gunicorn.socket /etc/systemd/system/
    - cp /var/www/portal/configs/gunicorn.service /etc/systemd/system/
    - systemctl start gunicorn.socket
    - systemctl enable gunicorn.socket
    - echo "GUNICORN sucessfully started"
    - cp /var/www/portal/configs/portal /etc/nginx/sites-available/
    - ln -s /etc/nginx/sites-available/portal /etc/nginx/sites-enabled
    - nginx -t && sudo systemctl restart nginx
    - echo "NGINX sucessfully started"
    - echo "SCRIPT sucessfully worked"
