stages:
    - test
    - build


test:
    stage: test
    script:
    - echo "APPLICATIONS test"
#    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /var/www/portal
#    - echo "APPLICATIONS sucessfully copied"


# Сборка Docker-образа
build:
    stage: build
    script:
        # собственно сборка и запуск проекта
        - docker-compose build
        - docker-compose up -d


