stages:
    - copy
    - build


copy:
    stage: copy
    script:
    # копирование данных проекта
    - echo "APPLICATIONS start copy"
    - rsync -av --no-perms --no-owner --no-group --exclude ".git*" $CI_PROJECT_DIR/ /var/www/portal
    - echo "APPLICATIONS sucessfully copied"


# Сборка Docker-образа
build:
    stage: build
    script:
        # собственно сборка и запуск проекта
        - docker-compose build
        - docker-compose up -d


