version: '2'

services:
  web:
    build: ./portal
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./portal:/var/www/portal
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev