version: '3'

services:
  web:
    build: .
    command: gunicorn Portal.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/portal/static
    expose:
      - 8000
    env_file:
      - /var/www/portal/.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal
      - POSTGRES_DB=portal_dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/var/www/portal/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: