version: '2'

services:
  web:
    build: /var/www/portal
    command: gunicorn Portal.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=portal
      - POSTGRES_PASSWORD=portal
      - POSTGRES_DB=portal_dev
#
#  nginx:
#    build: ./nginx
#    ports:
#      - 1337:80
#    depends_on:
#      - web

volumes:
  postgres_data: