# Generated by Django 4.0.3 on 2022-04-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_author',
            field=models.ImageField(default='user.jpg', upload_to='profile_images/'),
        ),
    ]
