# Generated by Django 4.0.3 on 2022-04-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmanager', '0002_alter_task_options_alter_task_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('queue', 'В очереди'), ('work', 'В работе'), ('done', 'Выполнено'), ('cancel', 'Отменённая')], default='new', max_length=32, verbose_name='Статус '),
        ),
    ]
