# Generated by Django 4.0.3 on 2022-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmanager', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('QUEUE', 'В очереди'), ('WORK', 'В работе'), ('DONE', 'Выполнено'), ('CANCEL', 'Отменённая')], default='NEW', max_length=32, verbose_name='Статус '),
        ),
    ]
